### ISSUE TITLE
xslt 4

### ISSUE THREAD

**Issue by laurenmcguigan** [ebeshero/DHClass-Hub#234]
Okay, so I am trying to output the headlines, but they are all running together as one inside the same span element. Which I do not understand because when I did the exact same thing on xslt 2 it worked...

```
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:math="http://www.w3.org/2005/xpath-functions/math" exclude-result-prefixes="xs math"
    xmlns="http://www.w3.org/1999/xhtml" version="3.0">
    <xsl:output method="xhtml" encoding="utf-8" doctype-system="about:legacy-compat"
        omit-xml-declaration="yes"/>

    <xsl:template match="/">
        <html>
            <head>
                <title>>HTML Transformation of 1888-07-30 Nelson Article</title>
            </head>

            <body>
                <h1> Chicago Times </h1>
                <h2>CITY SLAVE GIRLS</h2>
                <h3>Nell Nelson</h3>
                <h3>Monday Morning, July 30, 1888.</h3>

                <h4><xsl:apply-templates select="//head"/></h4>
            </body>
        </html>
    </xsl:template>

    <xsl:template match="head">
<span class="headLine"><xsl:apply-templates select="descendant::headLine"/></span>
    </xsl:template>



</xsl:stylesheet>
```

**Comment by laurenmcguigan** [comment]
Nevermind I figured it out...

**Comment by laurenmcguigan** [comment]
Okay new question... I am trying to match on the  working conditions whose tone is good. So I am putting the match into xpath to try and figure out how to grab them, but I keep getting errors. This is what the xpath looks like:

//workingConditions/@category = (//toneElements/connotation/@tone="good")

**Comment by RJP43** [comment]
@laurenmcguigan Great thinking going to the XPATH window to test your expressions!! Okay so the code in this document is really wonky (hence the reason the Nelson project has changed its code since) and I think some of that wonkiness is messing with your expression. So let's look at the pieces. In the article a working condition looks like this: 
`<workingConditions category="positive">I was treated with civility, however, and
        given permission to “drop in a week or so.”</workingConditions>`
Now if you are trying to find all of the working conditions **that have** an `@category` attribute that matches the `<category>` elements in the `<toneElements>` section that have `@tone="good"` then you are looking at these elements from the `<toneElements>` section: 
````
<category id="camaraderie" tone="good"/>
<category id="positive" tone="good"/>
````
Okay so instead of setting the `@category` of your `<workingConditions>` element equal to the `@tone` of the `<connotation>` elements (like you have in your above expression.) You instead want the `<workingConditions>` **that have** `@category` equal to the `@id` attributes of the `<category>` elements **that have** `@tone="good"` 

`//articleBody//workingConditions[@category=//toneElements/category[@tone='good']/@id]`

See how this statement is setting the two things that have the same text linked up (the `@id` of the `<category>` element and the `@category` of the `<workingConditions>` element. Where your expression was trying to set an `@tone` attribute equal to the `@category` of the `<workingConditions>` element.

**Comment by RJP43** [comment]
Hoping this helps clear up the wonkiness of the code:
![screenshot_1](https://cloud.githubusercontent.com/assets/8645521/19776628/d5aa8a88-9c42-11e6-9b89-6f5585dc7bb9.jpg)

**Comment by RJP43** [comment]
So as an XPATH challenge how would you get ANY element in `<articleBody>` with an associated bad connotation?

**Comment by jonhoranic** [comment]
@laurenmcguigan I am assuming you used the self contained line break element `<br/>` to break down the block text. I am having the same problem and I am trying what I can with no results.

**Comment by jonhoranic** [comment]
After an hour's worth of troubleshooting and reading (and re-reading ) the examples and tutorial links, I solved my first problem with the block of text! Now on to the rest of the assignment I have yet to touch!

**Comment by PPH3** [comment]
Any insight into the headline element? I coded for the heading info and am trying to style the core elements.

**Comment by jonhoranic** [comment]
@PPH3 I assume you set up all the HTML header elements `<h1>`, `<h2>`, etc. so where you need to look now is at the "applied-templates" from the class example. Focus on the ones that use the `mode=` attribute thing that allows you carry the rules down to your "templates," that should allow you to tackle all of those headlines.

**Comment by jonhoranic** [comment]
@PPH3 At least I think it works? I am trying to wrap this up for tonight, I know I have some holes in my code but I want to see if what I have done so far is correct. That and I still need to write the CSS style sheet, so its back to reading tutorials!

**Comment by jonhoranic** [comment]
After all that I noticed that the "voice" elements were not being displayed. I would guess there is some error going on with my XSLT that is going over my head, because I would think it would have worked! I am going to turn this in and practice some more with the solution when it is posted to get a better handle on this. See you all in class!

**Comment by RJP43** [comment]
Hi all ( @msb81 @laurenmcguigan @jonhoranic @PPH3 @etj27 @mjb232 @JaredKramer40 @setriplette @ahunker ) 

@ebeshero and I have agreed to extend [XSLT Exercise 4](http://www.newtfire.org/dh/XSLTExercise4.html)'s due date to Monday (10/31). That means both  [XSLT Exercise 4](http://www.newtfire.org/dh/XSLTExercise4.html) and  [XSLT Exercise 5](http://www.newtfire.org/dh/XSLTExercise5.html) are due Monday. If you already turned in something for XSLT Exercise 4 no worries you can upload over top of it in Courseweb and we will download the latest uploaded files on Monday for grading (if you run into issues uploading to Courseweb email your submission to rjp396@gmail.com).

**Comment by RJP43** [comment]
@PPH3 I am posting your submitted code here to help highlight some of the bigger issues I think multiple people are facing with this file. 
````
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    exclude-result-prefixes="xs"
    xmlns="http://www.w3.org/1999/xhtml" version="3.0">
    <xsl:output method="xhtml" encoding="utf-8" doctype-system="about:legacy-compat"
        omit-xml-declaration="yes"/>
<xsl:template match="/">
    <html>
        <head>
            <title>1888-07-30 Nelson Article</title>
        </head>
    <body>
        <h1>Chicago Times</h1>
        <h2>CITY SLAVE GIRLS</h2>
        <h3>Monday Morning, July 30, 1888</h3>
        <h4>Nell Nelson</h4>
     <xsl:apply-templates select="//head"/>
    </body>
    </html>
</xsl:template>
<xsl:template match="/">
    <span class="headline"><xsl:apply-templates select="//head[headline]"/></span>
<!--can't get the headline elements to post-->
</xsl:template>
</xsl:stylesheet>
````
First, instead of writing out the contents of your `<h1>` to `<h4>` elements why not instead call on the elements that contain this data in the XML using an apply-templates selection in each of these HTML heading elements. For example instead of `<h3>Monday Morning, July 30, 1888</h3>` using `<h3><xsl:apply-templates select="//head/date"/></h3>` allows your XSLT to be more usable in case you were applying this XSLT over any, similarily-coded article. The big picture here is to imagine writing a project XSLT stylesheet that can be run over all of the similar documents in a project to output multiple HTML pages. An XSLT that uses apply-templates selections pulls from the hierarchy which we can imagine will be the same across similar files; whereas, your heading elements only make this XSLT useful for this single article. 

The first task of the assignment is to lay out the parts of the XML source code that can be called upon once in the **single** document node match (`<xsl:template match="/">`) using apply-templates (like on `<byline>`, `<newspaperTitle>`, etc.) and then identifying where further processing needs to be done in separate template matches (like on `<headLine>` and `<articleBody>`. Now the elements that need further processing still get selected in the document node match where they are expected to fall in relation to the other selections, but they also get templates after the document node template match **matching** on their interior elements and designating how those specific elements inside of those other elements (selected in the document node match) are processed further (be it  with `<span> @class`, added surrounding text, etc.). 

SOOOOOO your XSLT in the document node template match will have a series of apply-templates selections sitting inside a variety of HTML elements (ie. heading elements) and logically placed apply-template selections sitting outside of HTML tags that tell XSLT that the portion of the document called in that selection will appear there (in that specific spot) in the HTML, but will be processed further in a later template match that details how the interior elements/text are processed. Then your other templates will match on the other elements we have asked you to transform in the assignment. 

See my above conversation with @laurenmcguigan discussing the relation between `<articleBody>` elements and the `<toneElements>` section of the source document and ping me as you guys have further (detailed!) questions on where you are getting caught up.

**Comment by RJP43** [comment]
Also, people seem to be confused about this part of the assignment: 

_Besides wrapping your <xsl:apply-templates/> in <span> elements and other HTML elements (Hint: including HTML heading elements say if you want each of your <headLine> elements to appear as individual headings instead of block text) you might consider adding extra spaces or text outside some of these as well. For example, in our HTML output note that each of the voice tags have some added words appearing in front of the quoted speeches (where the sex of the speaker or if Nelson was the speaker is indicated). Also, we added double `<br/>` elements to add space around the blocks of dialogue. Use what you think looks best and provides the most readable HTML output._

We are  simply saying that instead of wrapping every element we asked you to transform in `<span> @class` elements you might instead simply add linebreaks (`<br/>`) or text outside of the contents. So the example we give and that can be seen in the output file is of us adding extra space around the portions of dialogue. To do this we created a template match on the dialogue elements inside of `<articleBody>` and we place numerous `<br>` before and after the `<xsl:apply-templates/>` (we just so happened to also wrap replace the dialogue tags with the `<span> @class` setup). So in our output HTML the dialogue has been transformed from this (in the XML): 
````
<dialogue>
          <mascVoice>“Well?”</mascVoice>.<unclear/> 
          <femVoice>“I brought the mate back.”</femVoice>
          <mascVoice connotation="negative">“Oh, you have, eh?”</mascVoice>
</dialogue>
````
to this (in the HTML): 
````
<br /><br />
<span class="dialogue">
           DIALOGUE TEXT IN HERE!!! 
           Inserted from the <xsl:apply-templates/> 
           in the XSLT template 
</span>
<br /><br />
````

**Comment by ahunker** [comment]
I am having a lot of trouble with this assignment, nothing seems to be working for me. Someone please look at the code I have so far and tell me where I'm going wrong. I feel like I have too many apply-templates because I'm having to seek out certain elements individually.
```
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:math="http://www.w3.org/2005/xpath-functions/math" exclude-result-prefixes="xs math"
    xmlns="http://www.w3.org/1999/xhtml" version="3.0">
    <xsl:output method="xhtml" encoding="utf-8" doctype-system="about:legacy-compat"
        omit-xml-declaration="yes"/>
    <xsl:template match="/">
        <html>
            <head>
                <title>HTML Transformation of 1888-07-30 Nelson Article</title>
                <link rel="stylesheet" type="text/css" href="Hunker_Oct_28_XSLT_04.css"/>
            </head>
            <body>
                <h1><xsl:apply-templates select="//head/newspaperTitle"/></h1>
                <h2><xsl:apply-templates select="//head/seriesTitle"/></h2>
                <h3><xsl:apply-templates select="//head/date"/></h3>
                <h3><xsl:apply-templates select="//head/byline"/></h3>
                <h4>
                    <xsl:apply-templates select="descendant::head//headLine"/>
                </h4>
                <p>
                    <xsl:apply-templates select="descendant::articleBody"/>
                </p>
            </body>
        </html>
    </xsl:template>
    <xsl:template match="descendant::head//headLine">
        <span class="headLine"><xsl:apply-templates/></span><br/>
    </xsl:template>
    <xsl:template match="descendant::articleBody">
        <xsl:apply-templates/>
    </xsl:template>
    <xsl:template match="descendant::articleBody//dialogue">
        <br/><xsl:apply-templates/><br/>
    </xsl:template>
    <xsl:template match="descendant::articleBody//dialogue/femVoice">
        <br/><span class="femVoice"><xsl:apply-templates/></span>
    </xsl:template>
    <xsl:template match="descendant::articleBody//dialogue/mascVoice">
        <br/><span class="mascVoice"><xsl:apply-templates/></span>
    </xsl:template>
    <xsl:template match="descendant::articleBody//dialogue/nellVoice">
        <br/><span class="nellVoice"><xsl:apply-templates/></span>
    </xsl:template>
    <xsl:template match="descendant::articleBody//company[@name='identified']">
        <span class="company"><xsl:apply-templates/></span>
    </xsl:template>
    <xsl:template match="descendant::articleBody//workingConditions[@category='positive']">
        <span class="positive"><xsl:apply-templates/></span>
    </xsl:template>
    <xsl:template match="descendant::articleBody//workingConditions[@category='negative']">
        <span class="negative"><xsl:apply-templates/></span>
    </xsl:template>
</xsl:stylesheet>
```
All I know is when I tried to do something like this:
```
<xsl:template match="descendant::articleBody//dialogue">
<span class="femVoice><xsl:apply-templates select="/femVoice"/></span>
<span class="mascVoice><xsl:apply-templates select="/mascVoice"/></span>
<span class="nellVoice><xsl:apply-templates select="/nellVoice"/></span>
</xsl:template>
```
It puts the dialogue in the order I have listed above and shoves all of the femVoice dialogue into one element, all the mascVoice into one element, and all the nellVoice into one element. The same thing happened when I tried to distinguish the workingConditions. I've looked over the tossed salad example but it's not helping me out. I also don't think I have my CSS linked correctly.

**Comment by RJP43** [comment]
@ahunker This assignment does call for a lot of template matches because we are asking you to transfer several of the XML elements into "CSS-grabbable" HTML elements. Just as a reference point our XSLT has 9 template matches (including the document node match) and we can imagine a solution to have even more pending on how you grab the `@tone` values. Looking at your above code there are only a few issues, but you should be getting some kind of output. When you say "nothing seems to be working" does that mean you are not getting output or that the output is just not what you expected?

**Comment by RJP43** [comment]
@ahunker Your CSS looks linked correctly, but as you have it linked your CSS file will need to be sitting on the same level as the XSLT file and your output HTML file.

**Comment by RJP43** [comment]
@ahunker the glaring issues I see with your XSLT both have to do with the one-to-one versus many-to-one setup. 
So first, your document node match looks great up until this `<h4><xsl:apply-templates select="descendant::head//headLine"/></h4>`. Let's think about what this is saying .... do you really want one `<h4>` element surrounding all of the headlines? I get what you were thinking here and you are dead on by placing an apply-templates selection on the headlines here but in order to get each of the headlines individually wrapped in `<h4>` elements you want to move that HTML tag down into your template match on headlines. 

Now since all of the text of the articleBody sits inside that single `<articleBody>` element you did well by calling on it one time in the document node match and outputting all of that text in an HTML `<p>` tag, but you don't need to then write another separate template match on `<articleBody>` to output that text because you already are doing that by your apply-templates selection in the document node template match. 

Rightfully, the rest of your template matches drill down into elements within that text being output in the `<p>` tag and output with the various other HTML markup you specify in those matches.

**Comment by RJP43** [comment]
Think of it like this: 

In your document node match, you are saying how you want the main structure of the HTML document to look. So you specify where certain parts of the source XML document will appear in the HTML document and you include all of the HTML tags you expect to appear only once. 

Then your other template matches say okay now that you have this text appearing here in the HTML (by the document node match) I want to grab these other specific pieces (elements) from inside that specified part of the XML to transform them into HTML tags. So all of your template matches will start from the point grabbed in the source document node match, but then drill down into the elements that you need to grab and transform.

**Comment by RJP43** [comment]
@ahunker Oh jeeze the other thing is that your template matches should be landing on XPath patterns, not full XPath expressions. Simply remove all of those `descendant::` declarations in your template matches to take those from full expressions to XPath patterns.

**Comment by ahunker** [comment]
I am getting output, but I wasn't sure if I had too many `<xsl:template>` in my document. My CSS is on the same level as my other documents, but should I be seeing the effect of the CSS on the transformed document that I'm working on? Also, I tried shifting the headLine elsewhere but it's still wrapping all of the headLines in one h4 element. This is what I changed it to:
```
<h4>
     <xsl:apply-templates select="//head"/>
</h4>
<xsl:template match="//head">
     <span class="headLine"><xsl:apply-templates select="//headLine"/></span>
</xsl:template>
```
I just fixed up the descendant:: issue as well.

**Comment by RJP43** [comment]
@ahunker You should be able to see the styling on your output HTML file ... sometimes you can't see it in the output window so you might try opening it in your browser (command + O and finding the file) to see it there. Now as for your headlines the reason you still get all of the headlines in a single `<h4>` element is becuase you have the `<h4> element in the document node match instead of in the separate template match that is process all of your headlines individually. You can apply templates in your document node match without surrounding it in an HTML element since you are processing that portion of the XML again in a following template match.

**Comment by RJP43** [comment]
@ahunker also the leading slashes on head in your template match is still an xpath expression instead of an xpath patten.

**Comment by ahunker** [comment]
Ok, I think I've figured out where I was going wrong and how to fix it for now. Thank you! I may be back with more questions later.

**Comment by RJP43** [comment]
Happy to help... and Okay :)
