### ISSUE TITLE
XSLT Exercise 6 -- working with output file vs. xslt stylesheet

### ISSUE THREAD

**Issue by kes213** [ebeshero/DHClass-Hub#387]
I just want to clarify something before I begin working. 

As I'm inserting the links, am I adding the <a> tags to the templates on my XSLT spreadsheet, or am I adding them directly to the html output file? 

I know that the sorting happens within an XSLT spreadsheet, but I'm confused as to how the links would work on the spreadsheet as well.

**Comment by ghbondar** [comment]
@kes213 The links should be added automatically by the XSLT-stylesheet that you are coding. 
Please see our [posted example on GitHub](https://github.com/ebeshero/DHClass-Hub/blob/master/Class-Examples/XSLT/modalXSLT-collections/collections_example/Sonnets-linked-coll.xsl)

**Comment by kes213** [comment]
Okay, here's what I have as far as creating the links. 

```
<xsl:template match="body" mode="toc">
        <li>
            <a href="#p{//teiHeader/fileDesc/indo}"><xsl:apply-templates select="child::head/title" mode="toc"/>
            <xsl:text> ~ </xsl:text>
            <xsl:apply-templates select="(lg/l)[1]" mode="toc"/></a>
        </li>
    </xsl:template>
```
The only thing is  `<a href=#p>`

Is it a problem with the way I've stepped down to the **indo** element?

**Comment by ebeshero** [comment]
@kes213 Check your spelling! It's an `idno` element, as in "id number". You've got `indo`.

**Comment by pab124** [comment]
I have a question about the alphabetical sort part of the assignment.  So far, I've managed to reproduce the table of contents under a heading of "first lines alphabetically". I did the whole
`<xsl:apply-templates ....(all the stuff necessary to get the first lines identified>
<xsl:sort>
</xsl:apply-templates>`
and when I run it, it just gives me back the original order of the poems. Am I not applying the `<xsl:sort>` element correctly?

**Comment by ebeshero** [comment]
@pab124 Presumably you've set your `@select` attribute on `<xsl:apply-templates select="descendant::something" mode="toc" >` right? `<xsl:sort>` takes its context from the XPath location you've set in the `@select` attribute, but you can refine that with *another* `@select` that you can set on `<xsl:sort>` itself. In order to get it to sort on the first lines, you may need to step from the context you've set in `<xsl:apply-templates>` to the specific thing you need to sort on. Does that help?

**Comment by pab124** [comment]
So, if I have something like this 
`<xsl:template match="body" mode="FLI">
       <li>
           <a href="#{/TEI//idno}"><strong><xsl:apply-templates select="descendant::title" mode="FLI"/></strong></a><xsl:text>: </xsl:text>
           <xsl:apply-templates select="lg[1]/l[1]">
                <xsl:sort/>
            </xsl:apply-templates>
       </li>
    </xsl:template>`
are you suggesting that maybe, as it is written, I would have to change `<xsl:sort/>` to `<xsl:sort select="lg[1]/l[1]"`? Do i have to specifically tell it to sort the first lines even if they're mentioned within the templates i'm trying to sort?

**Comment by ebeshero** [comment]
@pab124 AHA! Now I understand the problem! You are attempting to sort **too far in** to the process. Keep in mind that this particular template you're matching is processing each poem--you are already **inside** a file in the collection when you run this. So there's nothing to *sort* on--there's only ONE first line inside each poem.

**Comment by ebeshero** [comment]
@pab124 You need to reposition your `<xsl:sort>` so it runs when you are invoking the entire collection--up in the template match in which you invoke the collection as a whole. Does that make sense?

**Comment by pab124** [comment]
@ebeshero I understand the idea you're saying, but I'm not sure how to act upon it. That is, I'm not sure where I 'invoke the collection as a whole'.

**Comment by ebeshero** [comment]
@pab124 Remember where you used the collection variable, to refer to the collection of Dickinson poems? Set your sort at the point where you apply-templates to something in terms of that collection variable.

**Comment by ebeshero** [comment]
@pab124 Check out our example of this posted here in DHClass-Hub in Class-Examples --> XSLT...that might help!

**Comment by ebeshero** [comment]
@pab124 See https://github.com/ebeshero/DHClass-Hub/blob/master/Class-Examples/XSLT/modalXSLT-collections/collections_example/Sonnets-linked-coll.xsl

**Comment by pab124** [comment]
@ebeshero Oh, I see now. I was working in the completely wrong part of the document then. Once I looked at that, everything seems to be working now. Thank you very much for your help.

**Comment by ebeshero** [comment]
@pab124 Huzzah! Glad to help. 👍

**Comment by kes213** [comment]
@ebeshero I fixed the spelling of my idno element, but it's still only giving me the "p" in my output.

**Comment by ebeshero** [comment]
@kes213 Is `<idno>` a child of `<fileDesc>`? Look again!

**Comment by ebeshero** [comment]
@kes213 Always check your XPath over in the XPath window on one of the source documents in the collection...

**Comment by kes213** [comment]
I saw that earlier, and I made a change, but I'm still not getting output. 

```
 <h2 id="p{//teiHeader/fileDesc/msIdentifier/idno}">
                <xsl:apply-templates select="child::head/title"/>
            </h2>
```

**Comment by ebeshero** [comment]
@kes213 Still not quite! Try running the XPath you wrote on any one of the Dickinson XML files...this won't turn up the `<idno>`. You're just one step off, though: `msIdentifier` is not a direct child of `fileDesc`. Also, there's a simpler way to reach `<idno>`. You can leap down from the document node straight to it without taking those microsteps...

**Comment by kes213** [comment]
Okay, I got it to work. Thank you!

**Comment by ebeshero** [comment]
Huzzah!

**Comment by ebeshero** [comment]
G'night DH-ers! See you in the morning...student-mentor team may be awake, but your profs are out for the night. Zzzzzz....
